version: '3.7'
services:

  front-envoy:
    # volumes:
      # - type: volume
        # source: bla
        # target: /etc/
        # volume:
          # nocopy: false
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
      - "443"
    ports:
      - "8000:80"
      - "8001:8001"
      - "443:443"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    # volumes:
      # - type: volume
        # source: config
        # target: /etc/
        # volume:
          # nocopy: false
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service
    # volumes:
      # - type: volume
        # source: config
        # target: /etc/
        # volume:
          # nocopy: false
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
  
  springboot:
    build:
      context: .
      dockerfile: Dockerfile-auth
    networks:
      - envoymesh
    expose:
      - "8090"
    ports:
      - "8090:8090"

networks:
  envoymesh: {}

#volumes:
#  bla: