# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer="Yassir.bonyad@gmail.com"

# The application's jar file
ARG JAR_FILE=authentication/target/*.jar

# Add the application's jar to the container
ADD ${JAR_FILE} auth.jar

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/auth.jar"]