version: '3.7'
services:

  front-envoy:
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
      - "443"
    ports:
      - "8000:80"
      - "8001:8001"
      - "443:443"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
  
  springboot:
    build:
      context: .
      dockerfile: Dockerfile-auth
    networks:
      - envoymesh
    expose:
      - "8090"
    ports:
      - "8090:8090"

networks:
  envoymesh: {}